import sys, io, os, time, warnings
sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding='utf-8'); warnings.filterwarnings('ignore')
import pandas as pd, numpy as np
from sklearn.model_selection import StratifiedKFold, cross_val_predict
from sklearn.preprocessing import OrdinalEncoder
from sklearn.metrics import roc_auc_score, average_precision_score
from sklearn.ensemble import RandomForestClassifier, ExtraTreesClassifier
from sklearn.linear_model import LogisticRegression
from catboost import CatBoostClassifier
from lightgbm import LGBMClassifier
from xgboost import XGBClassifier

DATA = 'Astram event data_anonymized - Astram event data_anonymizedb40ac87.csv'
df = pd.read_csv(DATA, low_memory=False)
df['t']=pd.to_datetime(df['created_date'],errors='coerce'); df=df.sort_values('t').reset_index(drop=True)
df['lat']=pd.to_numeric(df['latitude'],errors='coerce'); df['lon']=pd.to_numeric(df['longitude'],errors='coerce')
df['hour']=df['t'].dt.hour.fillna(0).astype(int); df['weekday']=df['t'].dt.weekday.fillna(0).astype(int)
y=df['requires_road_closure'].astype(int).values; N=len(df); base=y.mean()
cats=['event_type','event_cause','veh_type','corridor','police_station','zone']; nums=['lat','lon','hour','weekday']
for c in cats: df[c]=df[c].astype(str).fillna('NA')
codes=OrdinalEncoder(handle_unknown='use_encoded_value',unknown_value=-1).fit_transform(df[cats]).astype(int)
X=pd.DataFrame(codes,columns=cats)
for c in nums: X[c]=df[c].astype(float).values
cat_idx=list(range(len(cats)))

# SAME random CV splits the existing TabPFN random OOF was generated on
rcv=list(StratifiedKFold(5,shuffle=True,random_state=0).split(X,y))

mk={
 'CatBoost'    : lambda: CatBoostClassifier(iterations=400,depth=6,learning_rate=0.05,verbose=0,random_seed=0,cat_features=cat_idx,thread_count=-1),
 'LightGBM'    : lambda: LGBMClassifier(n_estimators=400,learning_rate=0.05,num_leaves=31,random_state=0,n_jobs=-1,verbose=-1),
 'XGBoost'     : lambda: XGBClassifier(n_estimators=400,learning_rate=0.05,max_depth=6,tree_method='hist',random_state=0,n_jobs=-1,eval_metric='logloss'),
 'RandomForest': lambda: RandomForestClassifier(n_estimators=500,n_jobs=-1,random_state=0,class_weight='balanced'),
 'ExtraTrees'  : lambda: ExtraTreesClassifier(n_estimators=600,n_jobs=-1,random_state=0,class_weight='balanced'),
}
fitkw={'LightGBM': lambda tr:{'categorical_feature':cat_idx}}

def oof_for(name, make):
    oof=np.full(N,np.nan); t0=time.time()
    for tr,te in rcv:
        m=make(); m.fit(X.iloc[tr],y[tr],**fitkw.get(name,lambda tr:{})(tr))
        oof[te]=m.predict_proba(X.iloc[te])[:,1]
    print(f'  {name:13s} OOF done  AUC={roc_auc_score(y,oof):.4f} PR={average_precision_score(y,oof):.4f} ({time.time()-t0:.0f}s)',flush=True)
    np.save(f'oof_random_{name}.npy', oof); return oof

print(f'N={N} base={base:.4f} pos={y.sum()}',flush=True)
print('\n=== Training tree models on RANDOM CV (matches TabPFN random OOF splits) ===',flush=True)
oofs={}
for name in mk: oofs[name]=oof_for(name, mk[name])
# TabPFN random OOF already generated by tabpfn_test.py on identical splits
tab=np.load('oof_tabpfn_random.npy')
assert not np.isnan(tab).any(), 'TabPFN random OOF has NaNs'
oofs['TabPFN']=tab
print(f'  {"TabPFN":13s} OOF load  AUC={roc_auc_score(y,tab):.4f} PR={average_precision_score(y,tab):.4f}',flush=True)

ORDER=['CatBoost','LightGBM','XGBoost','RandomForest','ExtraTrees','TabPFN']
M=np.column_stack([oofs[m] for m in ORDER])

# 1) standalone scores
print('\n=== STANDALONE OOF SCORES (random CV) ===')
print(f'{"model":13s}  {"AUC":>7s}  {"AP":>7s}  {"AP-lift":>7s}')
for m in ORDER:
    a=roc_auc_score(y,oofs[m]); p=average_precision_score(y,oofs[m])
    print(f'{m:13s}  {a:7.4f}  {p:7.4f}  {p/base:7.2f}x')

# 2) correlation matrix of OOF predictions (Spearman = rank corr, robust for AP)
print('\n=== CORRELATION MATRIX of OOF predictions (Spearman) ===')
R=pd.DataFrame(M,columns=ORDER).corr(method='spearman')
print(R.round(3).to_string())

# helper: cross-fitted logistic stacker AP over a set of columns
def stack_ap(cols, seed=1):
    Ms=np.column_stack([oofs[c] for c in cols])
    p=cross_val_predict(LogisticRegression(max_iter=1000,class_weight='balanced'),
                        Ms,y,cv=StratifiedKFold(5,shuffle=True,random_state=seed),
                        method='predict_proba')[:,1]
    return average_precision_score(y,p), roc_auc_score(y,p), p

# 3) AP contribution of each model = drop in full-stack AP when that model is removed (leave-one-out)
ap_full,_,_=stack_ap(ORDER)
print('\n=== AP CONTRIBUTION (leave-one-out drop in full 6-model stack AP) ===')
print(f'full 6-model stack AP = {ap_full:.4f}')
contrib=[]
for m in ORDER:
    rest=[c for c in ORDER if c!=m]
    ap_wo,_,_=stack_ap(rest)
    contrib.append((m, ap_full-ap_wo))
    print(f'  drop {m:13s} -> stack AP={ap_wo:.4f}  contribution={ap_full-ap_wo:+.4f}')

# 4) stack AP WITH vs WITHOUT TabPFN  (the decision metric)
trees=['CatBoost','LightGBM','XGBoost','RandomForest','ExtraTrees']
ap_wo,auc_wo,_=stack_ap(trees)
ap_w ,auc_w ,_=stack_ap(trees+['TabPFN'])
delta=ap_w-ap_wo
print('\n=== STACK AP: WITH vs WITHOUT TabPFN ===')
print(f'  stack WITHOUT TabPFN (5 trees)      AP={ap_wo:.4f}  AUC={auc_wo:.4f}')
print(f'  stack WITH    TabPFN (5 trees+PFN)  AP={ap_w:.4f}  AUC={auc_w:.4f}')
print(f'  ΔAP from adding TabPFN = {delta:+.4f}')
print(f'\nDECISION RULE: keep TabPFN iff ΔAP >= +0.0050')
print('  >>> ' + ('KEEP TabPFN (ΔAP >= 0.005)' if delta>=0.005 else 'ASK USER (ΔAP < 0.005)'))

pd.DataFrame(M,columns=ORDER).to_csv('oof_random_all_models.csv',index=False)
R.to_csv('oof_correlation_matrix.csv')
print('\nsaved: oof_random_<model>.npy, oof_random_all_models.csv, oof_correlation_matrix.csv')
