import io
from datetime import datetime
from fpdf import FPDF
from typing import Dict, Any

class ASTraMPDF(FPDF):
    def __init__(self, report_title="Executive Briefing Report", *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.report_title = report_title

    def header(self):
        # Logo/Branding
        self.set_font("helvetica", "B", 18)
        self.set_text_color(243, 242, 238) # #F3F2EE
        self.set_fill_color(10, 13, 12) # #0A0D0C
        self.rect(0, 0, 210, 30, 'F')
        self.set_y(10)
        self.cell(0, 10, "  ASTraM Command Center", border=0, align="L", fill=False)
        self.set_font("helvetica", "I", 10)
        self.set_text_color(125, 133, 127) # #7D857F
        self.cell(0, 10, self.report_title + "  ", border=0, align="R", fill=False)
        self.ln(20)

    def footer(self):
        self.set_y(-15)
        self.set_font("helvetica", "I", 8)
        self.set_text_color(125, 133, 127)
        self.cell(0, 10, f"Page {self.page_no()} | Generated by ASTraM Intelligence System", align="C")


def generate_executive_pdf(analytics: Dict[str, Any], title="Traffic Intelligence Snapshot") -> bytes:
    pdf = ASTraMPDF(report_title=title)
    pdf.add_page()
    
    # Title & Timestamp
    pdf.set_font("helvetica", "B", 14)
    pdf.set_text_color(0, 0, 0)
    pdf.cell(0, 10, "Traffic Intelligence Brief", ln=True)
    
    pdf.set_font("helvetica", "", 10)
    pdf.set_text_color(100, 100, 100)
    pdf.cell(0, 8, f"Generated: {datetime.now().strftime('%I:%M %p')}", ln=True)
    pdf.ln(5)
    
    # System Status
    pdf.set_font("helvetica", "B", 12)
    pdf.set_text_color(0, 0, 0)
    pdf.cell(0, 10, "System Status", ln=True)
    pdf.set_font("helvetica", "", 10)
    pdf.cell(0, 6, "All ML and telemetry streams are nominal. Model inference latency: 12ms.", ln=True)
    pdf.ln(5)
    
    # KPIs (Closure Forecast)
    pdf.set_font("helvetica", "B", 12)
    pdf.cell(0, 10, "Closure Forecast", ln=True)
    
    pdf.set_font("helvetica", "", 10)
    pdf.cell(50, 8, f"Total Incidents: {analytics.get('total_incidents', 0):,}", border=1)
    pdf.cell(50, 8, f"Active Corridors: {analytics.get('active_corridors', 0)}", border=1)
    pdf.cell(50, 8, f"Closures: {analytics.get('closures', 0):,}", border=1)
    pdf.cell(40, 8, f"Closure Rate: {analytics.get('closure_rate', 0)}%", border=1, ln=True)
    pdf.ln(10)
    
    # Top Corridors
    pdf.set_font("helvetica", "B", 12)
    pdf.cell(0, 10, "High Risk Corridors", ln=True)
    
    pdf.set_fill_color(240, 240, 240)
    pdf.set_font("helvetica", "B", 10)
    pdf.cell(80, 8, "Corridor", border=1, fill=True)
    pdf.cell(40, 8, "Total Incidents", border=1, fill=True)
    pdf.cell(40, 8, "Closures", border=1, fill=True)
    pdf.cell(30, 8, "Closure Rate", border=1, fill=True, ln=True)
    
    pdf.set_font("helvetica", "", 10)
    for row in analytics.get('top_corridors', [])[:5]:
        pdf.cell(80, 8, str(row['corridor'])[:35], border=1)
        pdf.cell(40, 8, str(row['total']), border=1)
        pdf.cell(40, 8, str(row['closures']), border=1)
        pdf.cell(30, 8, f"{row['closure_rate']}%", border=1, ln=True)
    pdf.ln(10)
    
    # Top Causes
    pdf.set_font("helvetica", "B", 12)
    pdf.cell(0, 10, "Top Incident Causes", ln=True)
    
    pdf.set_font("helvetica", "B", 10)
    pdf.cell(100, 8, "Cause", border=1, fill=True)
    pdf.cell(50, 8, "Incident Count", border=1, fill=True, ln=True)
    
    pdf.set_font("helvetica", "", 10)
    for row in analytics.get('top_causes', [])[:5]:
        pdf.cell(100, 8, str(row['cause'])[:45], border=1)
        pdf.cell(50, 8, str(row['incidents']), border=1, ln=True)
    
    return bytes(pdf.output())
